### ISSUE TITLE
No sd card usage.

### ISSUE THREAD

**Issue by schwabe** [eduvpn/android#1]
Just saw this:
- the app downloads an OVPN file to external storage and then launches OpenVPN, can this be also done differently? I don't want to leave OVPNs all around the external storage, and I want to not require this permission in the first place...

You could just use a Content provider and pass the content:/// uri to the app. Or in the case of OpenVPN for Android even use the API for that (see the remoteExample in ics-openvpn)

**Comment by fkooman** [comment]
Yeah, that seems to way to go. I am pretty new to Android development :)

I guess ideally either the API of OpenVPN for Android, or an embedded OpenVPN for Android makes the most sense, then it will also be a lot easier to update the VPN configuration if that is required, i.e. point to other hosts/ports, update cipher configuration etc through a backchannel the app uses to contact the VPN service API or something.

Is this all possible without embedding OpenVPN for Android? Currently both OpenVPN for Android and OpenVPN Connect are supported by this app... but I wouldn't mind dropping OpenVPN Connect support if that brings considerable advantages :)

**Comment by schwabe** [comment]
Yes. The api offers the possibility to either add/overwrite a Profile from OpenVPN for Android or to connect with a supplied configuration file. If there is something missing I can probably add the missing API.
