### ISSUE TITLE
handle revoked token

### ISSUE THREAD

**Issue by fkooman** [eduvpn/android#101]
if the user revokes the client in the user portal, the client should handle this gracefully. This means:

1. the access_token no longer works
2. the refresh_token no longer works

The app finds this out when there is a 401 response for a non expired token on the API endpoint, or when the refresh token no longer works at the OAuth endpoint to obtain a new access token when the current one expired.

Indicate this to the user and ask if the user wants to start the browser flow again to obtain token.

**Comment by fkooman** [comment]
This is standard OAuth 2.0.

**Comment by dzolnai** [comment]
Working as expected.
