### ISSUE TITLE
remove provider does not remove certificate

### ISSUE THREAD

**Issue by fkooman** [eduvpn/android#113]
after removing provider the certificate doesn't seem to be deleted. Adding the provider again, it reuses the old certificate.

**Comment by dzolnai** [comment]
Fixed

**Comment by fkooman** [comment]
not fixed in latest version.

**Comment by dzolnai** [comment]
Sorry, overlooked a code path.

**Comment by fkooman** [comment]
This is still not fixed with 1.3.1 actually...

1. remove all servers from app
2. re-add one of the servers that was already added before
3. connect: the old certificate is (still) used

**Comment by fkooman** [comment]
Easy to reproduce on vpn.tuxed.net with latest build of LC branded app:

1. fully remove the app
2. add server
3. delete server
4. add server again
5. it is still using the old certificate

**Comment by dzolnai** [comment]
Verified using your methods, should be fixed now 🤞
