### ISSUE TITLE
Show "Connection Info" when no notifications are available

### ISSUE THREAD

**Issue by fkooman** [eduvpn/android#121]
Now always the "Notifications" field is shown and receives focus when connecting.

In case there are no notifications, it makes more sense to either:

1. focus on "Connection Info" instead of on "Notifications";
2. do not show the "Notifications" at all, only "Connection Info".

See also the [styling](https://github.com/eduvpn/artwork/tree/master/styling) for Windows for an example of how to implement this.

**Comment by dzolnai** [comment]
I would prefer point 1, for a consistent experience. Otherwise it might be unclear for the users where the notifications have gone, if there are none.

**Comment by dzolnai** [comment]
Good idea, will implement it.

**Comment by dzolnai** [comment]
Fixed with #193
