### ISSUE TITLE
(auto) configuration update does not work

### ISSUE THREAD

**Issue by fkooman** [eduvpn/android#123]
Before connecting to a VPN the configuration for that VPN needs to be downloaded. It seems the latest dev version does not do this. 

On f26.tuxed.net we changed the configuration to disable compression, this breaks client configurations so it needs a new one to keep working.

Expected behavior: before connecting to VPN download the configuration through the API and use it.

**Comment by dzolnai** [comment]
https://github.com/eduvpn/android/pull/135

**Comment by fkooman** [comment]
So far wasn't able to find a problem here! I tested this by enabling/disabling `tlsCrypt` on a profile and then trying to reconnect. Works!
