### ISSUE TITLE
Implement an L2TP IPsec VPN for android

### ISSUE THREAD

**Issue by Khsed4** [eduvpn/android#126]
Hello, everyone, I hope u do well.
I want to implement an L2TP IPsec  VPN for android which connects to my server (I have my own server).
I have researched a lot but till now I couldn't find a good solution, so my question is here : 
**Can I use eduvpn or some of it's  classes to implement this kind of VPN to connect to my own server?**

**Comment by fkooman** [comment]
No, unfortunately you cannot. eduVPN only supports OpenVPN.

**Comment by Khsed4** [comment]
@fkooman  sorry for the second question.
Do you have any information if OpenVPN is compatible with this kind of VPN?

**Comment by fkooman** [comment]
I think Android has native support for L2TP. See e.g. https://www.privateinternetaccess.com/pages/client-support/android-l2tp on how to configure it.

You may also want to look into Algo VPN: https://github.com/trailofbits/algo if you are looking for a secure standards based VPN solution.

**Comment by Khsed4** [comment]
@fkooman thanks for your response, but about the algo project on Anti-features section it says :
**does not support legacy cipher suites or protocols like L2TP, IKEv1, or RSA** 
and as you know I need an L2TP IPsec PSK VPN.
By the way, I really appreciate your response, and please if you know something else, don't hesitate to share it.
