### ISSUE TITLE
expired certificate not automatically renewed

### ISSUE THREAD

**Issue by fkooman** [eduvpn/android#130]
when a certificate expires, the Android app will not automatically obtain a new one. This MUST be implemented.

We ran into this issue by using certificates that expired after 2 days.

**Comment by dzolnai** [comment]
https://github.com/eduvpn/android/pull/135
Using the check_certificate call.

**Comment by fkooman** [comment]
![screenshot from 2018-05-01 14-42-20](https://user-images.githubusercontent.com/616885/39473212-ee0850f2-4d4d-11e8-984a-e60487960397.png)

Maybe you can fix the header text a bit... It is not necessarily "unexpected".

**Comment by fkooman** [comment]
Also, when the certificate is disabled, it should not automatically try to fetch a new one, but that is a minor detail (see API.md).

**Comment by fkooman** [comment]
Also, when the `reason` indicates the user is disabled, it shouldn't try and fetch a new keypair. it will work as the API is not disabled, but the app won't be able to connect. There is no further feedback anymore for the user.

**Comment by fkooman** [comment]
![screenshot from 2018-05-01 15-25-31](https://user-images.githubusercontent.com/616885/39474362-ecda526a-4d53-11e8-9475-79246f18e902.png)

Don't see anything in `adb logcat` what it refers to.
