### ISSUE TITLE
deal with revoked tokens

### ISSUE THREAD

**Issue by fkooman** [eduvpn/android#14]
A user may revoke the permission of the app so it is no longer possible to query for user/system notifications/messages. In that case (when a 401 is received from the API endpoint) the app needs to request new authorization from the authorization endpoint (after performing a new discovery at `info.json`).

**Comment by fkooman** [comment]
See also https://tools.ietf.org/html/rfc6750#section-3.1

**Comment by fkooman** [comment]
if you "unauthorize" the app, the list of profiles cannot  be "fetched" anymore, it should automatically try to get a new access token.

**Comment by dzolnai** [comment]
I can only get a new one by opening the browser and asking the user to log in, so I can't automatize this. Any suggestions?

**Comment by fkooman** [comment]
Yeah, so I guess the browser needs to be opened...

**Comment by dzolnai** [comment]
What I mean is that we should probably tell the user somehow what is happening and why :)
I mean you open the app, and it would immediately throw the user into a random login screen because a token was outdated.

**Comment by fkooman** [comment]
Yeah, maybe a "popup" with some kind of text, e.g. "Unable to retrieve profile list. Retry?" or something and that that would open the browser to try and get a new access token.

**Comment by dzolnai** [comment]
Tap on the warning text to see the options
