### ISSUE TITLE
Simplify OAuth authorize dialog

### ISSUE THREAD

**Issue by fkooman** [eduvpn/android#142]
![screenshot from 2018-05-01 15-09-12](https://user-images.githubusercontent.com/616885/39473949-d73e52d2-4d51-11e8-9c93-899511463087.png)

* "Resources Missing" is too vague, showing this text does not help the user;
* "Could not connect to all providers" is also redundant so text can be removed as it shows the provider below;
* What does the "OK" button do? Why is it there?
* Don't show all servers that have authorization problems at once, but only one at a time;
* Move the check to when the user actually clicks on a profile, not on application start.

Better:

```
${PRODUCT_NAME} is no longer allowed to access "frkovpn.tuxed.net".

[ Reauthorize ] [ Remove ]
```

**Comment by fkooman** [comment]
This issue is related to #141, but is a simple first step to improve the UX substantially for the user.

**Comment by dzolnai** [comment]
This dialog has been removed from the app. Closing.
