### ISSUE TITLE
determine whether or not to use custom tabs automatically

### ISSUE THREAD

**Issue by fkooman** [eduvpn/android#144]
https://stackoverflow.com/questions/23611548/how-to-find-default-browser-set-on-android-device/23622337#23622337

automatically enable custom tabs when default browser is Chrome, otherwise disable.

**Comment by fkooman** [comment]
the goal is to remove the settings toggle for the user, no need to bother the user when it can be decided automatically.

**Comment by fkooman** [comment]
I remember hearing something about Firefox also supporting custom tabs?

**Comment by dzolnai** [comment]
> the goal is to remove the settings toggle for the user, no need to bother the user when it can be decided automatically.

The toggle is not there for auto-detection. That already works fine. There are people who don't like custom tabs, so we provide a way to disable them.

> I remember hearing something about Firefox also supporting custom tabs?

Yes, and the app supports it. Also custom tabs with the Samsung S Browser.

**Comment by fkooman** [comment]
So nothing to be done here anymore? Great!

**Comment by dzolnai** [comment]
Well you could remove the toggle if you want to, but it never hurts to have that extra option in my opinion :)

**Comment by fkooman** [comment]
Great! Thanks!
