### ISSUE TITLE
do not require a GitHub account with SSH key to download sources

### ISSUE THREAD

**Issue by fkooman** [eduvpn/android#17]
Now, the submodules point to "git@github.com" which as far as I know requires a SSH connection, which in turn requires a GitHub account with linked SSH public key. This is not convenient when building on a machine that is not your desktop.

**Comment by dzolnai** [comment]
Duplicate of #8. I'm waiting for another pull request to update the link.

**Comment by fkooman** [comment]
Oops! Sorry.
