### ISSUE TITLE
Bug in removing profile while having multiple providers 

### ISSUE THREAD

**Issue by shaanen** [eduvpn/android#174]
![image](https://user-images.githubusercontent.com/9215678/50283521-646bdd80-0456-11e9-92b5-6faa9aa103f9.png)

After removing a profile while having more than 1 provider, the profile will reappear at the bottom of the list. Trying to connect to the removed profile or any other profile of the same provider will result in an error. Only after leaving and revisiting the page, the profiles of that provider will be removed from the list.

**Comment by dzolnai** [comment]
Not relevant anymore, because you now remove servers instead of profiles.
