### ISSUE TITLE
Fetch info.json *right before connect* and follow redirects

### ISSUE THREAD

**Issue by jornane** [eduvpn/android#178]
We've moved our eduVPN service to a new server, and updated our info.json file accordingly.
After being loaded, the app should look up the endpoints again at info.json, the other clients do this as well.

**Comment by fkooman** [comment]
https://github.com/eduvpn/documentation/commit/0787b3255f5cd3b65f182fc924bfa8988349f503

**Comment by dzolnai** [comment]
Redirects are now followed, also info.json is not cached anymore.
