### ISSUE TITLE
chrome as default browser on android

### ISSUE THREAD

**Issue by johnche** [eduvpn/android#180]
eduvpn uses chrome as browser when asked to log in, even when the system default is firefox.

This behavior changed once i switched custom tabs off (custom tabs is on as default in the settings) as described in the settings.

I think default should be default browser, as the name implies, and "custom tabs" should be opt-in, this makes more sense to me. 

Also would be nice if the custom tab option would mention whatever browser it would use (chrome in the case of android)

**Comment by fkooman** [comment]
This is a request to turn off "custom tabs" by default in the Android app, basically :)

**Comment by dzolnai** [comment]
@johnche Firefox supports Custom Tabs since release 57, and as per this issue https://github.com/openid/AppAuth-Android/issues/372#issue-341356938, AppAuth should select Firefox over Chrome, if that is indeed the default browser.
Which version of Firefox do you have installed on your device?

**Comment by johnche** [comment]
Firefox version 68.0.2

**Comment by dzolnai** [comment]
Thank you, I was able to reproduce it. Turns out that the AppAuth library version was before they applied the fix I have linked in my previous comment.
After updating to the latest version, it opens Firefox as expected :)

If you still want to turn off Custom Tabs by default, let me know.
