### ISSUE TITLE
Improve error display(s)

### ISSUE THREAD

**Issue by fkooman** [eduvpn/android#184]
Look through all error dialogs the app can show, and allow for viewing more details so if a user has a problem we can find out where exactly the problem is... now we have no idea! case in point:

![image](https://user-images.githubusercontent.com/616885/67475648-e4ef0200-f656-11e9-84e9-5024577d67fd.png)

**Comment by fkooman** [comment]
It could for example have a button "Show more" or something... it should contain enough information that a screenshot of the message will help us to determine what is going on exactly... if it is the device, the app or the server that's malfunctioning.

**Comment by dzolnai** [comment]
Should be fixed now.
