### ISSUE TITLE
On Android 7 (LineageOS without Google stuff) redirect URI does not work

### ISSUE THREAD

**Issue by fkooman** [eduvpn/android#199]
Whether or not you use https:// of org.eduvpn.app:// it doesn't seem to register it or pick it up, so the browser will just give an error. 

I have no idea if this has anything to do with the browser, it is the AOSP browser, not Google Chrome, or with missing Google Play services, or, or?  Does it work on a Android 7 emulator?

Maybe not important to fix...

**Comment by fkooman** [comment]
Turning off "custom tabs" doesn't help.

**Comment by dzolnai** [comment]
What error do you get in the browser? AOSP browser might be an issue, do you have any other (like firefox) to pinpoint the issue.

**Comment by fkooman** [comment]
My phone is so broken right now, will test later and re-open if needed.
