### ISSUE TITLE
when adding server with only 1 profile popup/screen flashes quickly

### ISSUE THREAD

**Issue by fkooman** [eduvpn/android#204]
1. Add vpn-dev.tuxed.net which has only one profile
2. When connecting the screen makes weird flash/popups that disappear very quickly

It seems the "choose profile" page is quickly shown, but then the app continues to the connecting screen... Better to really skip the "chose profile" screen...

Build 83

**Comment by fkooman** [comment]
This seems to be solved in build 84 as well...

**Comment by dzolnai** [comment]
Yep, added some nice animations, and the loading popup is also more pretty.

**Comment by fkooman** [comment]
Seems to be back!

**Comment by dzolnai** [comment]
Fixed
