### ISSUE TITLE
Inconsistent gradle builds

### ISSUE THREAD

**Issue by julianharty** [eduvpn/android#206]
A summary: I can build and install the subsidiary ics-openvpn project but the gradle tasks fail for several separate clones of this repo. I'm perplexed why this project doesn't build reliably and would appreciate any help to establish reliable, clean builds. I'm working on creating a CI process for this codebase (currently in a fork https://github.com/commercetest/android) and also on helping test the app. This is related to issue #201 where I was having other issues building the project a few hours before this issue emerged yesterday (6th Nov 2019)
## Building the eduVPN Android app ##
Snapshot of recent commits:
```
git branch
* master
```
```
git log --graph --oneline -U0 --submodule  | grep -E '^[*| /\\]+([0-9a-f]{7} |Submodule |> |$)'
*   3432e9d Merge pull request #202 from eduvpn/feature/server_selection
|\  
| * 1ebf7be Update readme
| * b4135ff Fix unit tests
| | Submodule ics-openvpn ca83c967..485110c2:
| |   > Set default flavor
```
Try to build the project:
```
./gradlew assembleBasicRelease

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:lintVitalBasicRelease'.
> Could not resolve all artifacts for configuration ':app:devDebugCompileClasspath'.
   > Could not resolve project :ics-openvpn-main.
     Required by:
         project :app
      > Unable to find a matching configuration of project :ics-openvpn-main:
          - None of the consumable configurations have attributes.
```
I've looked at the recent changes and cannot see an obvious reason why the main build now fails. I then created another fresh clone and ended up with the same error. So I decided to see if I could build the supporting project of ics-openvpn (which I could)
## Building ics-openvpn directly ##
Here are the steps I followed, I ended up with a debug APK being installed on one of my Android devices that was connected to my laptop.
```
git clone https://github.com/eduvpn/ics-openvpn.git
cd ics-openvpn/
git log -1

./gradlew tasks
swig -version

git submodule init
git submodule update

./gradlew check
./gradlew installDebug
```
My machine has SWIG version 
```
SWIG Version 4.0.1
Compiled with clang++ [x86_64-apple-darwin16.7.0]
Configured options: +pcre
```

Out of interest, that APK seems to have minimal functionality and crashes with an exception when I interact with it (let me know if you'd like me to create an issue on that project's site with the details, I'll assume not.)

**Comment by dzolnai** [comment]
Hey Julian,
First of all, the eduvpn *fork* of ics-openvpn was never meant to be built as a standalone version. The original ics-openvpn in the schwabe remote is the one which works as a standalone. However, we can't integrate that directly, because an app is not the same as a library. That's why we have the fork, to convert it into a library with as little changes as possible.

But back to the original issue. Can you check if you get further when you remove the line 
`isDefault.set(true)` (line 108) from `ics-openvpn/main/build.gradle.kts`?

**Comment by dzolnai** [comment]
Oh and if that does not help, then also try removing `isDefault = true` (line 62) from `app/build.gradle` (and keep the other one removed too).

**Comment by julianharty** [comment]
Sorry for the delay, I ended up making yet another fresh copy of the project as I saw an odd message from git diff in the subproject (ics-openvpn). In summary, removing first `isDefault.set(true)` (line 108) from `ics-openvpn/main/build.gradle.kts` had no visible effect. Then I also removed  `isDefault = true` (line 62) from `app/build.gradle` and re-ran the gradle task each time. It still fails with the same message:
```
./gradlew assembleDevRelease

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDevReleaseJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:devReleaseCompileClasspath'.
   > Could not resolve project :ics-openvpn-main.
     Required by:
         project :app
      > Unable to find a matching configuration of project :ics-openvpn-main:
          - None of the consumable configurations have attributes.
```

BTW: the git diff message is when I'm in the root of the sub-project, see below:
```
Julians-MBP:android julianharty$ vim ics-openvpn/main/build.gradle.kts 
Julians-MBP:android julianharty$ git status
On branch master
Your branch is up-to-date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)

	modified:   ics-openvpn (modified content)

no changes added to commit (use "git add" and/or "git commit -a")
Julians-MBP:android julianharty$ git diff
diff --git a/ics-openvpn b/ics-openvpn
--- a/ics-openvpn
+++ b/ics-openvpn
@@ -1 +1 @@
-Subproject commit 485110c222e76937516581a75fc63b3947287835
+Subproject commit 485110c222e76937516581a75fc63b3947287835-dirty
```
I've not seen this sort of diff message, however it appears in both of the workspaces where I've tried these edits. I would have expected it to simply show the edit in line 108 for `ics-openvpn/main/build.gradle.kts`.

**Comment by julianharty** [comment]
For completeness, here's confirmation that I commented out the relevant line in `app/build.gradle`:
```
vim app/build.gradle 
Julians-MBP:eduvpn_07Nov2019 julianharty$ git diff
diff --git a/app/build.gradle b/app/build.gradle
index 87e1052..9a5b010 100644
--- a/app/build.gradle
+++ b/app/build.gradle
@@ -59,7 +59,7 @@ android {
         // Android Studio uses the alphabetically first flavor as the default, so I selected a name which would precede "dev" (sadly, "default" is a reserved keyword)
         basic {
             dimension "product"
-            isDefault = true
+            // 07 Nov 2019 isDefault = true
         }
         dev {
             dimension "product"
Julians-MBP:eduvpn_07Nov2019 julianharty$ git status
On branch master
Your branch is up-to-date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   app/build.gradle

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	android/

no changes added to commit (use "git add" and/or "git commit -a")
```
I've also deleted that line (62) entirely - still no improvement.

**Comment by dzolnai** [comment]
What is you git diff if you cd into ics-openvpn?

**Comment by julianharty** [comment]
Phew, as expected:
```
Julians-MBP:eduvpn_07Nov2019 julianharty$ cd android/ics-openvpn/
Julians-MBP:ics-openvpn julianharty$ git diff
diff --git a/main/build.gradle.kts b/main/build.gradle.kts
index 194a4007..3f8e9d78 100644
--- a/main/build.gradle.kts
+++ b/main/build.gradle.kts
@@ -105,7 +105,7 @@ android {
         create("ui") {
             setDimension("implementation")
             buildConfigField("boolean", "openvpn3", "true")
-            isDefault.set(true)
+            // 07Nov2019 isDefault.set(true)
         }
         create("skeleton") {
             setDimension("implementation")
```

**Comment by dzolnai** [comment]
Can you try to execute
  
    ./gradlew :app:assembleBasicRelease

From the root of the repo?

**Comment by julianharty** [comment]
That one fails (I'm using a different macbook and another fresh clone of the project).
```
TouchPadPro:07-Nov-2019-Android julianharty$ ./gradlew :app:assembleBasicRelease
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
Task 'assembleBasicRelease' not found in project ':app'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s
```

FYI the app build targets are listed as:
```
./gradlew tasks --all | grep app
app:sourceSets - Prints out all the source sets defined in this project.
app:assemble - Assembles all variants of all applications and secondary packages.
app:assembleAndroidTest - Assembles all the Test applications.
app:build - Assembles and tests this project.
app:buildDependents - Assembles and tests this project and all projects that depend on it.
app:buildNeeded - Assembles and tests this project and all projects it depends on.
app:clean - Deletes the build directory.
app:cleanBuildCache - Deletes the build cache directory.
wrapper - Generates Gradle wrapper files.
app:buildEnvironment - Displays all buildscript dependencies declared in project ':app'.
app:components - Displays the components produced by project ':app'. [incubating]
app:dependencies - Displays all dependencies declared in project ':app'.
app:dependencyInsight - Displays the insight into a specific dependency in project ':app'.
app:dependentComponents - Displays the dependent components of components in project ':app'. [incubating]
app:help - Displays a help message.
app:model - Displays the configuration model of project ':app'. [incubating]
app:projects - Displays the sub-projects of project ':app'.
app:properties - Displays the properties of project ':app'.
app:tasks - Displays the tasks runnable from project ':app'.
app:uninstallAll - Uninstall all applications.
app:check - Runs all checks.
app:connectedCheck - Runs all device checks on currently connected devices.
app:deviceCheck - Runs all device checks using Device Providers and Test Servers.
app:compileLint
app:consumeConfigAttr
app:extractProguardFiles
app:lint
app:lintFix
app:preBuild
app:prepareKotlinBuildScriptModel
app:resolveConfigAttr
```

**Comment by julianharty** [comment]
An update: once I'd added the ANDROID_HOME environment variable, here's what I get for the your command (and `app:lint` for instance)

```
./gradlew :app:assembleBasicRelease

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:lintVitalBasicRelease'.
> Could not resolve all artifacts for configuration ':app:devDebugCompileClasspath'.
   > Could not resolve project :ics-openvpn-main.
     Required by:
         project :app
      > Unable to find a matching configuration of project :ics-openvpn-main:
          - None of the consumable configurations have attributes.
```

**Comment by julianharty** [comment]
Gradle tasks for `app` build targets are now:
```
TouchPadPro:07-Nov-2019-Android julianharty$ ./gradlew tasks  | grep app
assembleAndroidTest - Assembles all the Test applications.
wrapper - Generates Gradle wrapper files.
lintFix - Runs lint on all variants and applies any safe suggestions to the source code.
uninstallAll - Uninstall all applications.
```

BTW: There are now an insane number of app build targets when I add `--all`
```
./gradlew tasks --all | grep app | wc -l
     667
```
I can attach a list if that'd help.

**Comment by julianharty** [comment]
@dzolnai A quick update, and one where the ics-openvpn package happens to be at an earlier commit. I finally had the time to get the relevant (modern) Android SDK installed on my Ubuntu 16.04 LTS machine. I'd already cloned the repo and run the relevant git submodule command as we'd discussed earlier yesterday (06 Nov 2019).
```
julian@julian-ThinkPad-X220:~/sandbox/eduvpn/master_android/android/ics-openvpn$ git log -1
commit ca83c967aca33811bad81374150af96f1fab9e5d
Author: Dániel Zolnai <zoiddani@gmail.com>
Date:   Fri Nov 1 16:29:56 2019 +0100

    Add task dependencies
julian@julian-ThinkPad-X220:~/sandbox/eduvpn/master_android/android/ics-openvpn$ git branch
* (HEAD detached at ca83c96)
  master
julian@julian-ThinkPad-X220:~/sandbox/eduvpn/master_android/android/ics-openvpn$ cd ../..
julian@julian-ThinkPad-X220:~/sandbox/eduvpn/master_android$ git log -1
commit 1660b3e4ec23faafdb88ca4e86825f4432cfd00c
Author: Dániel Zolnai <dzolnai@users.noreply.github.com>
Date:   Wed Nov 6 15:11:38 2019 +0100

    Add clone command to README
julian@julian-ThinkPad-X220:~/sandbox/eduvpn/master_android$ git branch
* master
```
So this pre-dates your recent updates to ics-openvpn, etc.
However gradle still aborts with the same reported error:
```
julian@julian-ThinkPad-X220:~/sandbox/eduvpn/master_android$ ./gradlew :app:assembleBasicRelease

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:lintVitalBasicRelease'.
> Could not resolve all artifacts for configuration ':app:devDebugCompileClasspath'.
   > Could not resolve project :ics-openvpn-main.
     Required by:
         project :app
      > Unable to find a matching configuration of project :ics-openvpn-main:
          - None of the consumable configurations have attributes.
```
The last edits to both `app/build.gradle` and `android/ics-openvpn/main/build.gradle.kts` were on 1st November 2019 
```
julian@julian-ThinkPad-X220:~/sandbox/eduvpn/master_android$ git blame app/build.gradle | grep 2019-11
5b988a99 (Dániel Zolnai   2019-11-01 11:40:18 +0100  31) 
5b988a99 (Dániel Zolnai   2019-11-01 11:40:18 +0100  32)         // This excludes some pretty old ABIs such armeabi or mips. LibSodium-JNI still includes binaries for these, which
5b988a99 (Dániel Zolnai   2019-11-01 11:40:18 +0100  33)         // leads to some devices selecting these as the app ABI, but the OpenVPN library did not include a binary for these,
5b988a99 (Dániel Zolnai   2019-11-01 11:40:18 +0100  34)         // thus resulting in a crash.
5b988a99 (Dániel Zolnai   2019-11-01 11:40:18 +0100  35)         ndk {
5b988a99 (Dániel Zolnai   2019-11-01 11:40:18 +0100  36)             abiFilters 'arm64-v8a', 'x86', 'x86_64', 'armeabi-v7a'
5b988a99 (Dániel Zolnai   2019-11-01 11:40:18 +0100  37)         }
```
```
/home/julian/sandbox/eduvpn/master_android/android/ics-openvpn
julian@julian-ThinkPad-X220:~/sandbox/eduvpn/master_android/android/ics-openvpn$ git blame main/build.gradle.kts | grep 2019-11
ca83c967 (Dániel Zolnai 2019-11-01 16:29:56 +0100 121)     // Ensure native build is run before assets, so assets are ready to be merged into the apk
ca83c967 (Dániel Zolnai 2019-11-01 16:29:56 +0100 122)     libraryVariants.configureEach {
ca83c967 (Dániel Zolnai 2019-11-01 16:29:56 +0100 123)         mergeAssets!!.dependsOn(externalNativeBuildTasks)
```

**Comment by dzolnai** [comment]
I think I have found the issue.
Can you please add the following lines to your local.properties inside the root of the repo:
```
ndk.dir=/Users/dzolnai/Library/Android/sdk/ndk-bundle
sdk.dir=/Users/dzolnai/Library/Android/sdk
cmake.dir=/Users/dzolnai/Library/Android/sdk/cmake/3.10.2.4988404/
```
Please make sure that they point to the correct location of course :)

**Comment by julianharty** [comment]
Thank you for inverstigating the problem. I've tried your suggestion and created a suitable local.properties file in the root of the project (see below). I also checked each of the folders seems to be correct. 
```
TouchPadPro:07-Nov-2019-Android julianharty$ cat local.properties
ndk.dir=~/android-sdk/ndk-bundle
sdk.dir=~/android-sdk/sdk
cmake.dir=~/android-sdk/cmake/3.10.2.4988404/
```
Some more diagnostic info:
```
TouchPadPro:07-Nov-2019-Android julianharty$ env | grep ANDR
ANDROID_HOME=/Users/julianharty/android-sdk/

TouchPadPro:07-Nov-2019-Android julianharty$ ls -l $ANDROID_HOME
total 0
drwxr-xr-x   5 julianharty  staff  170  4 Nov 21:59 build-tools
drwxr-xr-x   3 julianharty  staff  102 31 Oct 14:16 cmake
drwxr-xr-x   8 julianharty  staff  272  4 Nov 21:59 licenses
drwxr-xr-x  23 julianharty  staff  782 31 Oct 13:45 ndk-bundle
drwxr-xr-x   3 julianharty  staff  102 31 Oct 13:32 patcher
drwxr-xr-x  19 julianharty  staff  646 31 Oct 14:16 platform-tools
drwxr-xr-x   4 julianharty  staff  136  4 Nov 22:00 platforms
drwxr-xr-x  14 julianharty  staff  476  4 Nov 21:59 tools
```
The first attempt to run the command was when I was in flight mode (no WiFi connection) and it seemed to be promising (see below), however when I then enabled WiFi it returned to the same error message :( [sorry]

```
TouchPadPro:07-Nov-2019-Android julianharty$ ./gradlew :app:assembleBasicRelease
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileBasicReleaseJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:basicReleaseAnnotationProcessorClasspath'.
   > Could not resolve androidx.databinding:databinding-compiler:3.5.1.
     Required by:
         project :app
      > Could not resolve androidx.databinding:databinding-compiler:3.5.1.
         > Could not get resource 'https://maven.google.com/androidx/databinding/databinding-compiler/3.5.1/databinding-compiler-3.5.1.pom'.
            > Could not GET 'https://maven.google.com/androidx/databinding/databinding-compiler/3.5.1/databinding-compiler-3.5.1.pom'.
               > maven.google.com: nodename nor servname provided, or not known
      > Could not resolve androidx.databinding:databinding-compiler:3.5.1.
         > Could not get resource 'https://jcenter.bintray.com/androidx/databinding/databinding-compiler/3.5.1/databinding-compiler-3.5.1.pom'.
            > Could not GET 'https://jcenter.bintray.com/androidx/databinding/databinding-compiler/3.5.1/databinding-compiler-3.5.1.pom'.
               > jcenter.bintray.com: nodename nor servname provided, or not known
      > Could not resolve androidx.databinding:databinding-compiler:3.5.1.
         > Could not get resource 'https://jitpack.io/androidx/databinding/databinding-compiler/3.5.1/databinding-compiler-3.5.1.pom'.
            > Could not GET 'https://jitpack.io/androidx/databinding/databinding-compiler/3.5.1/databinding-compiler-3.5.1.pom'.
               > jitpack.io: nodename nor servname provided, or not known

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
```
Enabled WiFi
```
TouchPadPro:07-Nov-2019-Android julianharty$ ./gradlew :app:assembleBasicRelease

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileBasicReleaseJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:basicReleaseCompileClasspath'.
   > Could not resolve project :ics-openvpn-main.
     Required by:
         project :app
      > Unable to find a matching configuration of project :ics-openvpn-main:
          - None of the consumable configurations have attributes.

```

**Comment by julianharty** [comment]
After reading some SO comments about gradle wanting a full path rather than relative paths I modified `ANDROID_HOME` and the 3 entries in `local.properties` to use full paths - still the same issue.
```
export ANDROID_HOME=/Users/julianharty/android-sdk/
TouchPadPro:07-Nov-2019-Android julianharty$ ls -l $ANDROID_HOME
total 0
drwxr-xr-x   5 julianharty  staff  170  4 Nov 21:59 build-tools
drwxr-xr-x   3 julianharty  staff  102 31 Oct 14:16 cmake
drwxr-xr-x   8 julianharty  staff  272  4 Nov 21:59 licenses
drwxr-xr-x  23 julianharty  staff  782 31 Oct 13:45 ndk-bundle
drwxr-xr-x   3 julianharty  staff  102 31 Oct 13:32 patcher
drwxr-xr-x  19 julianharty  staff  646 31 Oct 14:16 platform-tools
drwxr-xr-x   4 julianharty  staff  136  4 Nov 22:00 platforms
drwxr-xr-x  14 julianharty  staff  476  4 Nov 21:59 tools
TouchPadPro:07-Nov-2019-Android julianharty$ ./gradlew :app:assembleBasicRelease

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:lintVitalBasicRelease'.
> Could not resolve all artifacts for configuration ':app:devDebugCompileClasspath'.
   > Could not resolve project :ics-openvpn-main.
     Required by:
         project :app
      > Unable to find a matching configuration of project :ics-openvpn-main:
          - None of the consumable configurations have attributes.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
TouchPadPro:07-Nov-2019-Android julianharty$ cat local.properties 
ndk.dir=/Users/julianharty/android-sdk/ndk-bundle
sdk.dir=/Users/julianharty/android-sdk/sdk
cmake.dir=/Users/julianharty/android-sdk/cmake/3.10.2.4988404/
TouchPadPro:07-Nov-2019-Android julianharty$ 
```
I'm trying to find a way to get Gradle to show me whether it's reading and using the values from `local.properties` when it runs - any siggestions on how to do so would be great. I've tried `--debug` etc. but drown in text and cannot seem to be able to grep the output.

**Comment by dzolnai** [comment]
You can fix the jitpack.io error by replacing every occurence of `https://jitpack.io` in the build files, with `https://www.jitpack.io`.
Mainly in build.gradle and ics-openvpn/main/build.gradle.kts

**Comment by julianharty** [comment]
I think the issues with `jitpack.io` were only when I was in flight mode and Gradle couldn't connect to the internet. Nonetheless I'll have a go at changing these entries to see if they help at all.

**Comment by dzolnai** [comment]
> sdk.dir=/Users/julianharty/android-sdk/sdk

I think this should be:

    sdk.dir=/Users/julianharty/android-sdk/

**Comment by dzolnai** [comment]
@julianharty did that help?

**Comment by julianharty** [comment]
@dzolnai I think I've managed to work out what was going wrong and why. I'll try to explain, and then perhaps we can revise the README to reduce the chance of anyone else following the path I took.
<img width="416" alt="Screen Shot 2019-11-20 at 07 48 16" src="https://user-images.githubusercontent.com/785891/69219206-42994000-0b6a-11ea-8941-48f0d7e2e234.png">

1. When I first cloned the project I simply followed the usual `git clone` that github provides on the project's home page (see above for the screenshot). I then used the contents of the build scripts `builder_setup.sh` and `build_app.sh` which included commands to download the submodules, etc.
2. You updated `README.sh` and added examples of the commands to use. I used that `git clone` command `git clone --recurse-submodules https://github.com/eduvpn/android.git` **_However I did so in the current, already cloned repo since I was used to running the submodule git commands within an existing clone._** This meant that I effectively had 2 nested copies of the main Android app's codebase and only 1 of the sub-modules.
3. I remained in the same (root) folder that I'd initially cloned and was working in.
4. Gradle could 'see' the ics-openvpn project, however it couldn't find it where it expected it. So running `./gradlew tasks` etc. listed various build tasks related to it, however when it tried to build the app, etc. it failed to find the files it needed, and sadly the error messages weren't at all clear which exacerbated the confusion.

So, in summary, I got confused and gradle's behaviour and error messages misled me further and as I'd been conditioned to first clone the repo then initialise the submodules afterwards I managed to repeat the mistake several times on serveral machines.

I'm guessing there's no easy or practical way to stop GitHub displaying the default `git clone` instructions, so as a second-best alternative, perhaps we could revise the README file to tell people _NOT_ to use the default `git clone` command and to only use the command from the readme if they want to clone this repo?

BTW: I'm now playing catch-up to see if I can reliably build the app. Gradle commands such as `./gradlew check` currently fail with 3+ errors because of MissingPermissions e.g.:
```
./eduVPN/android/android/ics-openvpn/main/src/main/java/de/blinkt/openvpn/core/NetworkUtils.java:25: Error: Missing permissions required by ConnectivityManager.getNetworkInfo: android.permission.ACCESS_NETWORK_STATE [MissingPermission]
                  NetworkInfo ni = conn.getNetworkInfo(network);
                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by dzolnai** [comment]
I'll check how we can clarify the README.md based on your experience.
About the error: there are some additional lint checks done for you (no idea why they did not show up for me).
Until then, can you check if building with the extra flag `-x lint` works?

**Comment by julianharty** [comment]
The `-x lint` enables the command to run successfully. 

BTW: Does `ics-openvpn` need the `android.permission.ACCESS_NETWORK_STATE` permission? (the one lint claims is missing) and if so, is it actually missing? I can find it in https://github.com/eduvpn/android/blob/master/app/src/main/AndroidManifest.xml but not in the subproject.

Here's where the `./gradlew check` fails for the main (this) project:
```
* What went wrong:
Execution failed for task ':ics-openvpn-main:lint'.
```

And here are the 5 errors reported in the lint results file:
` grep --include=\*.xml -R "android.permission.ACCESS_NETWORK_STATE" *`
```
... removed various intermediate buid files...
ics-openvpn/main/build/reports/lint-results.xml:        message="Missing permissions required by ConnectivityManager.getActiveNetworkInfo: android.permission.ACCESS_NETWORK_STATE"
ics-openvpn/main/build/reports/lint-results.xml:        message="Missing permissions required by ConnectivityManager.getAllNetworks: android.permission.ACCESS_NETWORK_STATE"
ics-openvpn/main/build/reports/lint-results.xml:        message="Missing permissions required by ConnectivityManager.getNetworkInfo: android.permission.ACCESS_NETWORK_STATE"
ics-openvpn/main/build/reports/lint-results.xml:        message="Missing permissions required by ConnectivityManager.getLinkProperties: android.permission.ACCESS_NETWORK_STATE"
ics-openvpn/main/build/reports/lint-results.xml:        message="Missing permissions required by ConnectivityManager.getNetworkCapabilities: android.permission.ACCESS_NETWORK_STATE"
```

**Comment by julianharty** [comment]
Back to what confused me, here's an example where gradle *knew* about the ics-openvpn project, but then later couldn't find the project where it expected it.
```
./gradlew --dry-run --info | grep ics
Included projects: [root project '07-Nov-2019-Android', project ':app', project ':ics-openvpn-main']
> Configure project :ics-openvpn-main
Evaluating project ':ics-openvpn-main' using build file '/Users/julianharty/sandbox/eduVPN/07-Nov-2019-Android/ics-openvpn/main/build.gradle'.
```
I wonder if there's anything we can do easily to detect/check in the gradle files whether the sub-projects are in their expected locations - be great if we could, then we could add an explicit check and error message if anyone (including me) repeats the same mistake I was making.

**Comment by julianharty** [comment]
For the lint errors, one option is to suppress the errors in this project's related ics-openvpn project if we don't want to add the relevant permission to that project's manifest file. 

e.g. `@SuppressLint("MissingPermission")` as per https://github.com/square/picasso/pull/1663/files and https://github.com/square/picasso/issues/1662

**Comment by dzolnai** [comment]
> Does ics-openvpn need the android.permission.ACCESS_NETWORK_STATE permission? (the one lint claims is missing) and if so, is it actually missing? 

It is provided in the app manifest.

> I wonder if there's anything we can do easily to detect/check in the gradle files whether the sub-projects are in their expected locations - be great if we could, then we could add an explicit check and error message if anyone (including me) repeats the same mistake I was making.

Now that we have correct clone docs, I don't expect it to happen again.
If it does, then we can help debug in a ticket. We have to keep the documentation at a reasonable length :)

> For the lint errors, one option is to suppress the errors in this project's related ics-openvpn project if we don't want to add the relevant permission to that project's manifest file.

Those errors are only visible when you do `./gradlew check`, which checks the modules one-by-one, instead of doing a project level check.
As I said above, the missing permission is provided in the app manifest, so it is not missing globally. 
App build commands, such as `./gradlew assembleBasicRelease` should still work without an error :)
