### ISSUE TITLE
Adding more than 1 "Other Provider" not possible

### ISSUE THREAD

**Issue by fkooman** [eduvpn/android#209]
1. add one server through "Add other provider", e.g. vpn.tuxed.net.
2. works fine!
3. try to add another one, e.g. vpn-dev.tuxed.net
4. when coming back from the OAuth flow the app goes back to the "Add Provider" screen with the URL still visible
5. When going back to main screen, the added server is NOT visible...

I expect the VPN provider to be added to the list of VPN providers to connect to, and return to the main screen.

Build 84

**Comment by fkooman** [comment]
This is with "Use custom tabs" disabled. When it is enabled is *does* work.

**Comment by fkooman** [comment]
I hate "custom tabs" or not "custom tabs". If the app doesn't work with custom tabs disabled, it should probably be removed as an option :)

**Comment by dzolnai** [comment]
> I hate "custom tabs" or not "custom tabs". If the app doesn't work with custom tabs disabled, it should probably be removed as an option :)

It is just great for this. Not all users have custom tabs, so with a simple switch you can test that version too.

**Comment by fkooman** [comment]
I guess the main problem is that when "custom tabs" are off, the app never works when using the `https://` redirect URI. When it is on, it only works when Chrome is the default. Is this what's going on?

In any case, this should not be exposed to the users... maybe to testers yes, but final version should not have it. Can you detect the user's default browser? If `https://` redirect only works with "custom tabs" on and Chrome as default we should either document this properly, or switch back to custom URL scheme? Can you find more info about this perhaps?

**Comment by dzolnai** [comment]
By accident the viewmodel was scoped to the activity, instead of the fragment, resulting in multiple viewmodels listening to the same event, and triggering the browser flow twice immediately, which resulted in AppAuth remembering the incorrect state. Was a hard one to find out, but finally fixed :)

**Comment by fkooman** [comment]
Nice! :+1:
