### ISSUE TITLE
auhentication -> authorization

### ISSUE THREAD

**Issue by fkooman** [eduvpn/android#212]
https://github.com/eduvpn/android/blob/7f50feb244049d14a3bb8277a6cb7ee29b52df3d/app/src/main/res/values/strings.xml#L117

Actually this is _authorization_, not _authentication_.

**Comment by fkooman** [comment]
This occurs in many more places, also in the names of the variables...

**Comment by dzolnai** [comment]
Fixed it. The only remaining occurences are for the SavedAuthentication's, but that is how AppAuth calls those objects, so won't change those.
