### ISSUE TITLE
Gradle warnings

### ISSUE THREAD

**Issue by fkooman** [eduvpn/android#218]
> Configure project :ics-openvpn-main
WARNING: API 'variant.getMergeAssets()' is obsolete and has been replaced with 'variant.getMergeAssetsProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getMergeAssets(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
WARNING: API 'variant.getExternalNativeBuildTasks()' is obsolete and has been replaced with 'variant.getExternalNativeBuildProviders()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getExternalNativeBuildTasks(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.

**Comment by fkooman** [comment]
But this is probably in ICS openvpn...so nothing we can do about it, right?

**Comment by fkooman** [comment]
> > Task :app:compileHomeReleaseKotlin
w: /home/fkooman/Projects/eduvpn-android-20191121204213/app/src/main/java/nl/eduvpn/app/fragment/ProviderSelectionFragment.kt: (91, 103): Parameter 'v' is never used, could be renamed to _
w: /home/fkooman/Projects/eduvpn-android-20191121204213/app/src/main/java/nl/eduvpn/app/fragment/ProviderSelectionFragment.kt: (105, 107): Parameter 'v' is never used, could be renamed to _
w: /home/fkooman/Projects/eduvpn-android-20191121204213/app/src/main/java/nl/eduvpn/app/fragment/ProviderSelectionFragment.kt: (157, 13): Condition 'binding.providerList != null' is always 'true'
w: /home/fkooman/Projects/eduvpn-android-20191121204213/app/src/main/java/nl/eduvpn/app/utils/ErrorDialog.kt: (28, 20): 'NetworkInfo' is deprecated. Deprecated in Java

**Comment by fkooman** [comment]
That one above may be something in eduVPN/Let's Connect! app :)

**Comment by dzolnai** [comment]
Fixed both
