### ISSUE TITLE
Edu VPN ISSSUE

### ISSUE THREAD

**Issue by farazh12** [eduvpn/android#222]
Unable to find a matching configuration of project :ics-openvpn-main:
  - None of the consumable configurations have attributes.

How to solve this issue?

**Comment by dzolnai** [comment]
Hi @farazh12 

What exactly are you doing?
Do you have your ANDROID_HOME environment variable correctly set?
Did you clone the submodules?

**Comment by farazh12** [comment]
yes ANDROID_HOME is correctly set
but i have the above issues...

**Comment by dzolnai** [comment]
Check if you have made any changes by accident.
Also, what version of Android Studio are you running?

**Comment by farazh12** [comment]
no changes just compiled source code using android studio 3.5
