### ISSUE TITLE
guest access - "creating keypair" issue

### ISSUE THREAD

**Issue by efef** [eduvpn/android#233]
"secure internet" login, connecting to home-country (NL in my case) works fine.
When  try to add  a second or third country the next country hangs on this  screen:

![signal-2020-02-14-210018](https://user-images.githubusercontent.com/3393474/74564860-46bdd980-4f70-11ea-8bfb-ef709dca006b.jpeg)

when kill the  app - restart app - the country has been added and connecting works.

Pleases fix the "creating keypair" issue

**Comment by dzolnai** [comment]
Fixed with #234
