### ISSUE TITLE
enable signature checking for new discovery

### ISSUE THREAD

**Issue by fkooman** [eduvpn/android#237]
As we are still working on signatures for the discovery files this is currently disabled **in the new discovery scenario**.

**Comment by fkooman** [comment]
Files are now signed with my key (for now) 

```
untrusted comment: minisign public key 8466FFE127BCDC82
RWSC3Lwn4f9mhG3XIwRUTEIqf7Ucu9+7/Rq+scUMxrjg5/kjskXKOJY/
```

**Comment by fkooman** [comment]
See https://github.com/eduvpn/documentation/blob/v2/SERVER_DISCOVERY.md#signatures

**Comment by dzolnai** [comment]
Checks enabled and working :)
