### ISSUE TITLE
use "drop-down" for servers belonging to the same server group

### ISSUE THREAD

**Issue by fkooman** [eduvpn/android#249]
now they are listed, visually indistinguishable from each other or servers not part of the server group.

**Comment by fkooman** [comment]
these are now listed under `peer_list`.

**Comment by fkooman** [comment]
The Windows app does it like this:

![image](https://user-images.githubusercontent.com/616885/77329966-fed46400-6d1e-11ea-914c-7a0ff5543b54.png)
![image](https://user-images.githubusercontent.com/616885/77330009-0a278f80-6d1f-11ea-9146-e0a068b5e2ae.png)

**Comment by dzolnai** [comment]
What I see as a UI challenge here is that we need a list selection from the manually added servers and a dropdown selection for the organization servers. Combining the two might be confusing for the user.

**Comment by fkooman** [comment]
There's actually 3 types... 

1. Servers that have `peer_list` (secure internet);
2. Servers that have no `peer_list` (institute access);
3. Manually added servers

**Comment by fkooman** [comment]
In the Windows application the manually added servers are added under (2).

**Comment by fkooman** [comment]
![image](https://user-images.githubusercontent.com/616885/77331348-e36a5880-6d20-11ea-9005-0bd4141bccea.png)

This doesn't mean it *must* be like this, but it can serve as inspiration!

**Comment by dzolnai** [comment]
that makes it even more complicated :)

**Comment by fkooman** [comment]
I don't even know what is technically possible on Android... maybe you have some ideas yourself?

**Comment by dzolnai** [comment]
Using expandable groups now.
