### ISSUE TITLE
when more than one server is available for an org, only one is shown

### ISSUE THREAD

**Issue by fkooman** [eduvpn/android#250]
1. choose org that has more than 1 server 
2. choose one to login to
3. on the server list that is shown after successful authorizing at one server, the other servers from before are no longer shown...

**Comment by fkooman** [comment]
To be more specific: if you use FrkoIdP you'll have access to three servers which you initially can also choose, but after successfully authorizing one, you can never find the other two anymore...

**Comment by dzolnai** [comment]
Fixed.
