### ISSUE TITLE
update for new JSON format

### ISSUE THREAD

**Issue by fkooman** [eduvpn/android#253]
* `server_group_url` is gone
* `server_info_url` now is gone and needs to be constructed by the app based on `server_info`

See https://github.com/eduvpn/documentation/blob/v2/SERVER_DISCOVERY.md

**Comment by fkooman** [comment]
New discovery URL: `https://disco.eduvpn.org/organization_list.json`

**Comment by dzolnai** [comment]
Fixed, using the new URL now.
