### ISSUE TITLE
eduVPN app crashes if no profile is available for user

### ISSUE THREAD

**Issue by LongmanU** [eduvpn/android#262]
I use ACLs to check the logged in user's permissions in the eduVPN profile configuration. If no profile is available (ACL check fails for user), the app crashes instead of displaying an error message.

**Comment by fkooman** [comment]
I was able to reproduce this with the last stable release! 

I assume the application doesn't handle the situation where the call to `/profile_list` returns an empty list of profiles... Or something like this.

**Comment by dzolnai** [comment]
Fixed.
