### ISSUE TITLE
connect fails on test-server

### ISSUE THREAD

**Issue by efef** [eduvpn/android#267]
Our test-server is vpn.spoor.nu
The server https://vpn.spoor.nu is "special" in that it is configured to have quickly expiring tokens/certificates:
-browser session expires after 3 minutes (user needs to login every 3 minutes)
-issued OAuth refresh_token expires after 3 minutes
-generated X.509 certificates expire after 3 minutes
Every 15 minutes the server completely resets, so no tokens are valid anymore.

When I try to connect with the new beta on an android 8.1 device after authentication in browser the client app tries to connect, but is never connecting (icon stays yellow).

![signal-2020-04-01-233842](https://user-images.githubusercontent.com/3393474/78242122-c16f9380-74e1-11ea-9a66-823fcee1a1e6.jpeg)
![signal-2020-04-01-233849](https://user-images.githubusercontent.com/3393474/78242165-cfbdaf80-74e1-11ea-8648-7663e1b8a668.jpeg)

In log there isn't anything useful.

When I go back, click on VPN-profile, I get message "you're already connected"

Resetting the  config and relogin doesn't help me.

**Comment by dzolnai** [comment]
I can connect now on vpn.spoor.nu, fixed.
