### ISSUE TITLE
app is unreasonably slow

### ISSUE THREAD

**Issue by fkooman** [eduvpn/android#284]
the app is *very* slow:

1. fetching the organization list
2. choosing an organization (it takes ~10 seconds to open the browser after selecting an organization without feedback to the user)
3. the OAuth authorization itself goes very fast as that is done in the browser...
4. after approval the app just hangs for another 10 seconds before adding the server to the list (Again without user feedback)
5. "Discovering API..." and "Creating keypair" also takes 10+ second...
6. Connecting also takes forever...
7. When disconnecting you see the empty screen with "Add other server" for about 8 seconds before the added server appears again...
    - it seems there is network connectivity involved on the main screen before showing the added servers, this is not correct...

Once connected everything is fine, i.e. browsing the web goes normal speed. Also without VPN, browsing the web is fast without any noticeable delay...

**Comment by fkooman** [comment]
Don't notice anymore with the latest build...

**Comment by dzolnai** [comment]
I have added loading popups for when you come back after a disconnect. Also added better caching.
