### ISSUE TITLE
small text overlap in connection info

### ISSUE THREAD

**Issue by ghost** [eduvpn/android#289]
![signal-2020-07-05-120755](https://user-images.githubusercontent.com/616885/86530336-3f17b680-beb8-11ea-8f13-4a0b1ac8d2cb.jpeg)

**Comment by dzolnai** [comment]
Fixed.

**Comment by fkooman** [comment]
Not fixed yet in latest built actually.

**Comment by dzolnai** [comment]
I made some adjustments, hopefully it is fixed now. 
Otherwise we need to probably think about some design to fit everything.
