### ISSUE TITLE
disconnect toggle not active after returning to app

### ISSUE THREAD

**Issue by fkooman** [eduvpn/android#290]
1. start app
2. connect to server (choose server, choose profile, wait for it to connect)

So far so good, now:

3. tap the "back" button
4. nothing seems to happen...
5. tap the "back" button again
6. app launcher screen is shown with all apps
7. go back to the app

What happens:

the connection toggle is "greyed out", i.e. user cannot disconnect anymore.

What should happen:

the connection toggle should be toggleable.

Build: https://argon.tuxed.net/fkooman/eduVPN/eduVPN-20200705.apk
Android: Samsung A6, Android 10.

**Comment by fkooman** [comment]
![signal-2020-07-05-121424](https://user-images.githubusercontent.com/616885/86530460-1b08a500-beb9-11ea-9132-eefb34cd6199.jpeg)

**Comment by fkooman** [comment]
Also that you have to click the back button twice is a bug...

**Comment by dzolnai** [comment]
Fixed, also the back button bug.
