### ISSUE TITLE
document how to build without android studio

### ISSUE THREAD

**Issue by fkooman** [eduvpn/android#3]
is it possible to build without android studio?

**Comment by fkooman** [comment]
I tried it after installing a lot of versions of the SDK and build environments.

```
[fkooman@fralen eduvpn-android]$ ./gradlew build
Incremental java compilation is an incubating feature.
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:app:prepareComAndroidSupportAnimatedVectorDrawable2420Library
:app:prepareComAndroidSupportAppcompatV72420Library
:app:prepareComAndroidSupportDesign2420Library
:app:prepareComAndroidSupportRecyclerviewV72420Library
:app:prepareComAndroidSupportSupportCompat2420Library
:app:prepareComAndroidSupportSupportCoreUi2420Library
:app:prepareComAndroidSupportSupportCoreUtils2420Library
:app:prepareComAndroidSupportSupportFragment2420Library
:app:prepareComAndroidSupportSupportMediaCompat2420Library
:app:prepareComAndroidSupportSupportV42420Library
:app:prepareComAndroidSupportSupportVectorDrawable2420Library
:app:prepareDebugDependencies
:app:compileDebugAidl
:app:compileDebugRenderscript
:app:generateDebugBuildConfig
:app:mergeDebugShaders
:app:compileDebugShaders
:app:generateDebugAssets
:app:mergeDebugAssets
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources
:app:mergeDebugResources
:app:processDebugManifest
:app:processDebugResources
/home/fkooman/Projects/eduvpn-android/app/build/intermediates/res/merged/debug/values/values.xml:1510: AAPT: Error retrieving parent for item: No resource found that matches the given name 'blinkt'.
    
/home/fkooman/Projects/eduvpn-android/app/build/intermediates/res/merged/debug/values/values.xml:1518: AAPT: Error retrieving parent for item: No resource found that matches the given name 'blinkt.alertDialog'.
    
/home/fkooman/Projects/eduvpn-android/app/build/intermediates/res/merged/debug/values/values.xml:1521: AAPT: Error retrieving parent for item: No resource found that matches the given name 'blinkt.dialog'.
    
:app:processDebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/home/fkooman/Downloads/android-sdk-linux/build-tools/24.0.2/aapt'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 9.481 secs
```

**Comment by dzolnai** [comment]
Are you sure you have the submodules checked out? Check if you have a directory called ics-openvpn/main

**Comment by fkooman** [comment]
Yes:

```
[fkooman@fralen eduvpn-android]$ git submodule update --init --recursive
[fkooman@fralen eduvpn-android]$ ls -l ics-openvpn/main/
total 32
-rw-rw-r--.  1 fkooman fkooman  891 Sep 15 08:22 build.gradle
drwxrwxr-x.  2 fkooman fkooman 4096 Sep 15 08:22 jni
drwxrwxr-x. 13 fkooman fkooman 4096 Sep 15 08:22 lzo
drwxrwxr-x.  2 fkooman fkooman 4096 Sep 15 08:22 misc
drwxrwxr-x.  8 fkooman fkooman 4096 Sep 15 08:23 openssl
drwxrwxr-x. 14 fkooman fkooman 4096 Sep 15 08:23 openvpn
drwxrwxr-x.  3 fkooman fkooman 4096 Sep 15 08:22 ovpn3
drwxrwxr-x.  5 fkooman fkooman 4096 Sep 15 08:22 src
[fkooman@fralen eduvpn-android]$ 
```

**Comment by dzolnai** [comment]
Before build starts, do you see the message `Configuring x/3 projects`? (x can be any number from 1-3)
I have a hunch that somehow it doesn't want to pick up the `ics-openvpn` submodule.

**Comment by fkooman** [comment]
Yes I see those, up to 3 yes...

**Comment by dzolnai** [comment]
I just submitted a fix in #4. Can you check with that?
It was probably related to how Windows and Linux treat a path in a different manner.

**Comment by fkooman** [comment]
sure, you can directly push to the repo if you want! :)

**Comment by fkooman** [comment]
(I did it this time still) :-)

**Comment by dzolnai** [comment]
Usually someone else reviewes the code, so that the chance of introducing bugs is smaller :) But thanks for the quick merge.

**Comment by fkooman** [comment]
It works now!
```
[fkooman@fralen eduvpn-android]$ find | grep apk$
./app/build/outputs/apk
./app/build/outputs/apk/app-debug-unaligned.apk
./app/build/outputs/apk/app-debug.apk
./app/build/outputs/apk/app-release-unsigned.apk
[fkooman@fralen eduvpn-android]$ 
```

:-)

**Comment by fkooman** [comment]
I am still a bit confused on the details of the required SDK versions. I installed api level 24, but it also wanted api level 23 even though I couldn't find anything about that during my grep searches, not in the eduvpn app, nor in the openvpn-ics directory...

**Comment by dzolnai** [comment]
Are you sure it is required? I just removed it and cleant&rebuilt the project, and it still works fine.

**Comment by dzolnai** [comment]
The previous version of the app was using 23 btw.

**Comment by fkooman** [comment]
![screenshot from 2016-09-15 14-56-16](https://cloud.githubusercontent.com/assets/616885/18550852/2cdd9344-7b56-11e6-9fc2-4e0fbcec918c.png)

Alright, now it works! I installed the above packages on a clean extract of the SDK. Awesome! :)

**Comment by dzolnai** [comment]
Great! Closing then :)

**Comment by fkooman** [comment]
We should probably put this in the documentation somewhere.

**Comment by dzolnai** [comment]
Which part? :)

**Comment by fkooman** [comment]
the required dependencies, how to do this git submodule checkout etc, which commands to run :) not necessarily your task, but it would be useful to have :)

**Comment by dzolnai** [comment]
Missing dependencies will be reported by Gradle. It's also not a good idea to document, because they can change very frequently.
Submodule checkout is already documented.
Command can be documented, although it is common knowledge, since you know you want to build with Gradle.
But feel free to update the readme :)

**Comment by fkooman** [comment]
I meant the android-sdk dependencies, i.e. what you have to enable when install it :)

**Comment by dzolnai** [comment]
That's what I meant, we usually upgrade those when a new version of Android or the build tools is released, to be more compatible with them and have the latest bugfixes.
