### ISSUE TITLE
app tries to connect to wrong TCP ports when force TCP is enabled

### ISSUE THREAD

**Issue by fkooman** [eduvpn/android#30]
there are (currently) no processes listening at tcp/1194, tcp/1195 and tcp/1196 so there should be no attempts to connect to anything that is not listed as a `remote` in the configuration.

**Comment by sveeke** [comment]
In addition to Francois: the idea is that the app gets the configuration from the vpn server. This configuration contains the processes/openvpn-instances that are running at certain proto's and ports. So one server might for example only run udp/1194 and tcp/443 (in that order in the config) while another might run additional processes on udp/1195, udp/1196 etc. and tcp/1194. The server knows which ones are available and puts them in the configurations for the clients (this app).

**Comment by fkooman** [comment]
I updated the server code a bit, just FYI, it should not have any impact. The config you get back now is in the following form:

```
remote internet.vpn.tuxed.net 1195 udp
remote internet.vpn.tuxed.net 1194 udp
remote internet.vpn.tuxed.net 1194 tcp
remote internet.vpn.tuxed.net 443 tcp
```

(before there were 3 UDP entries, and only the 1 TCP entry for 443).

So the expected result of this is that when you "force TCP" it will try to connect to tcp/1194 first, and then to tcp/443 if that doesn't work.
