### ISSUE TITLE
session expiry time double

### ISSUE THREAD

**Issue by efef** [eduvpn/android#311]
![signal-2020-10-15-232204](https://user-images.githubusercontent.com/3393474/96187756-d53e8c80-0f3d-11eb-91c2-bc9d87ff868f.jpeg)

When eduVPN server has session time set to 1 day, the android app gives the expiry time in both hours and minutes. So it shows the session is 2 days. I guess it would be better to show only hours, and last hour count in minutes or so

**Comment by fkooman** [comment]
https://github.com/eduvpn/android/blob/ff2e2d6a2432c851ea380e237ee5f8ea300a2741/app/src/main/java/nl/eduvpn/app/viewmodel/ConnectionStatusViewModel.kt#L141

I think  `.div(60)` should be `.rem(3600)`, twice.  I am not sure if all the others are correct either, needs more review.

**Comment by fkooman** [comment]
It seems the `            // Expires within 30 days` is also wrong.

**Comment by fkooman** [comment]
As I don't have Android Studio or similar I'm just coding blind, please review the commit :)

**Comment by dzolnai** [comment]
Reviewed, looks good. Included in my PR (#313).

**Comment by fkooman** [comment]
Fixed in 2.0.2
