### ISSUE TITLE
No matching configuration of project

### ISSUE THREAD

**Issue by noshair** [eduvpn/android#312]
No matching configuration of project :ics-openvpn-main was found. The consumer was configured to find an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'implementation' with value 'ui', attribute 'product' with value 'basic', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' but:
  - None of the consumable configurations have attributes.

**Comment by noshair** [comment]
Please help me to fix and understand it better

**Comment by dzolnai** [comment]
Did you change anything in code?
It seems you are missing the fallback declaration, but we do have those in our build.gradle.
