### ISSUE TITLE
upstream ics-openvpn changes

### ISSUE THREAD

**Issue by fkooman** [eduvpn/android#32]
the ics-openvpn repo from schawbe was forked and modified. Please create a complete description of the changes to the 'official' release and their upstream status. 

E.g. this commit: what is the status of this in the official release? https://github.com/schwabe/ics-openvpn/commit/88a6088d972acda9ade78563d12bca97f3820f28

**Comment by fkooman** [comment]
Also, we should not depend on the egeniq fork of Openvpn for Android, but on the official one.

**Comment by dzolnai** [comment]
That's not possible. The original one is an application, not a library.

**Comment by fkooman** [comment]
Okay, then I propose the following:

- write a (shell) script that fetches a specific commit from the official upstream repo;
- work with upstream to incorporate your changes as much as possible;
- for all changes still required, create a separate patch (commit) and document why they cannot be upstreamed;
- just include the code directly in the repository (only source code!)

**Comment by dzolnai** [comment]
This one is a bit more complicated.
For now, I documented the changes in the readme of https://github.com/egeniq/ics-openvpn
We will discuss how we can make progress on the rest.

**Comment by fkooman** [comment]
One other thing... no repo should contain binary files, so maybe we need to run the NDK also when building the app. Hiding the binaries in `ics-openvpn/` does not count :P

**Comment by fkooman** [comment]
build from source moved to #50.

**Comment by dzolnai** [comment]
So we can close this one?

**Comment by fkooman** [comment]
no, this one is about upstreaming the changes to official ics-openvpn.

**Comment by dzolnai** [comment]
This one was merged: [#582](https://github.com/schwabe/ics-openvpn/pull/582)
This one was closed, because it needs to redone because of the separation of the process and UI: [#581](https://github.com/schwabe/ics-openvpn/pull/581). I will look into this one.
And finally I opened this issue, which has no reaction yet (is a more complex problem): [#583](https://github.com/schwabe/ics-openvpn/issues/583)

**Comment by dzolnai** [comment]
Instead of reopening the issue, I fixed it by doing it a different way: https://github.com/eduvpn/android/commit/ab5a401ea8b6342e4d7ff08a150d4bc07f2d4091
No further action needed anymore.
I already removed the commit from the ics-openvpn fork, so it should work fine.
