### ISSUE TITLE
Apps cannot be installed together

### ISSUE THREAD

**Issue by dzolnai** [eduvpn/android#325]
I discovered during testing of another issue, and I think this is a release blocker.
This probably got in with the last `ics-openvpn` update, because I don't remember seeing it before.

The issue is as following: when you have one of the following apps installed, you cannot install another of the following next to it: eduVPN, Let's Connect, OpenVPN for Android (the official app of the ics-openvpn lib).

The error I get is: `INSTALL_FAILED_CONFLICTING_PROVIDER`. It might be related to the FileProvider authority, which seems to be using the same authority across all apps.

**Comment by fkooman** [comment]
Is this easy to fix?

**Comment by dzolnai** [comment]
I don't think it will be too hard. I will try to take a look today.

**Comment by fkooman** [comment]
Thanks! I can confirm that installing OpenVPN for Android and the latest LC build don't install together.

**Comment by dzolnai** [comment]
Should be fixed by #326
