### ISSUE TITLE
 feature request "Renew session button" available within 24 hrs of expiry

### ISSUE THREAD

**Issue by efef** [eduvpn/android#348]
Some organisations use a very short session time, like 12 hours, their users like to be able to renew and extend the session any time during the day.
But the "Renew" should not be visable the first 30 minutes after authentication.

background about 30 minutes:

> 
>     the application SHOULD show a "Renew" button, starting from >= 30 minutes after
>     the OAuth authorization (using the browser) took place. The reason for this
>     30 minutes is that browser sessions in the portal are valid for 30 minutes
>     in eduVPN/Let's Connect! servers. Renewing before the user is forced to login
>     again results in getting a session that expires at the exact same time as the
>     previous one which is confusing to the user when they are trying out the
>     "Renew" button

**Comment by fantostisch** [comment]
Fixed by https://github.com/eduvpn/android/pull/343

**Comment by fantostisch** [comment]
This feature has been merged, issue can be closed.
