### ISSUE TITLE
"Force TCP" does not result in OpenVPN connection to profile prefering WireGuard

### ISSUE THREAD

**Issue by fkooman** [eduvpn/android#352]
When connecting to a profile that prefers to use WireGuard the client will still use WireGuard even when "force tcp" is enabled.

**Comment by fkooman** [comment]
It seems more subtle. It seems to (always) keep the same protocol it selected the first time it connected to a profile...

**Comment by fkooman** [comment]
Or... the "Force TCP" option change is ignored (in either direction)?

**Comment by fantostisch** [comment]
When changing the "Force TCP" option from the connection status screen, the setting was only applied when disconnecting, going back and selecting the server again. Fixed in https://github.com/eduvpn/android/pull/349/commits/3266f8f9eca2fc185cf0ed40df9fdeceb8b9bcd1.

**Comment by fantostisch** [comment]
Fix has been merged, issue can be closed.
