### ISSUE TITLE
Android 13 always on prevents disabling VPN

### ISSUE THREAD

**Issue by fkooman** [eduvpn/android#362]
It seems when using the eduVPN 3.0.0 app on Android 13 (GrapheneOS) it is not possible to disable the VPN anymore. When switching off the toggle (to disconnect) the VPN stays active. Also closing the app does not stop the VPN.

Settings -> Network & Internet -> VPN -> eduVPN 

"Always on" is activated there. If you disable the toggle there "Always-on VPN" the VPN gets disconnected.

What  should happen: if you disconnect *in the eduVPN app* the VPN should be deactivated.

**Comment by jwijenbergh** [comment]
Disconnecting works for me on a Pixel 6, stock ROM & also android 13. I do get a weird "connecting..." state (just hangs there) but not sure if that has to do with the always-on vpn setting because I am not sure how to reproduce it.

**Comment by fkooman** [comment]
Seems to be fixed in the latest version: https://grapheneos.org/releases#2022080300

Weird stuff.

**Comment by fkooman** [comment]
Okay, not fixed, I guess I once manually disabled "always on" under VPN and *then* it was okay. I'm not sure we can do anything about this.

When calling /disconnect the VPN config is invalided on the server, so always on definitely won't work anymore after that...

**Comment by fkooman** [comment]
For "normal" VPN providers this is not a problem of course as your config will remain valid indefinitely (until you stop your subscription).

**Comment by fkooman** [comment]
This needs to be manually fixed by disabling 'always on' VPN then all is good.

eduVPN/LC is not compatible with "always on" as the /disconnect call will invalidate the config on the server. So one should not call /disconnect in the case of always on, which means to never toggle off the VPN.

**Comment by fkooman** [comment]
This is GrapheneOS specific, they default to 'always on'
