### ISSUE TITLE
Remove "Use Custom Tabs" option

### ISSUE THREAD

**Issue by fantostisch** [eduvpn/android#372]
Proposal to remove the "Use Custom Tabs" option and always use them.

In my opinion this option should be in the browser app and not in our app. Besides, disabling custom tabs doesn't seem to work. With Firefox and Chrome installed it still uses custom tabs but just decides to ignore the default browser setting in system settings. On another device with Firefox and LineageOS default browser (which doesn't have custom tabs) it always opens a custom tab in Firefox.

Has anyone disabled the "Use Custom Tabs" option?

**Comment by jwijenbergh** [comment]
Custom tabs should be the default and the option be removed IMO

Why custom tabs are important to be on by default: https://support.google.com/faqs/answer/12284343?hl=en

How to detect if a browser supports custom tabs: https://developer.chrome.com/docs/android/custom-tabs/howto-custom-tab-check

**Comment by efef** [comment]
question is, why is this an issue, see https://github.com/eduvpn/android/issues/144

**Comment by dzolnai** [comment]
Custom tabs is not an option anymore, and is on by default. See [this comment above](https://github.com/eduvpn/android/issues/372#issuecomment-2301269033) why we did this.
