### ISSUE TITLE
Sort secure internet locations alphabetically

### ISSUE THREAD

**Issue by jwijenbergh** [eduvpn/android#381]
Cyprus is now at the bottom and Kenya is not before the M. I think more or less discovery had (by coincidence) sorted entries for secure internet but the app should not assume this also due to there being a difference in country names for other languages.

The app should sort this list alphabetically

![image](https://user-images.githubusercontent.com/46386452/225045223-2d0f9bb5-f7e8-4255-9d58-4b3fca67710f.png)

**Comment by dzolnai** [comment]
Fixed in latest version
