### ISSUE TITLE
Combined issue for lay-out improvements

### ISSUE THREAD

**Issue by sveeke** [eduvpn/android#39]
I seems a tad overdone to create issues for every small lay-out thing, so let's aggregate them here.

**Comment by sveeke** [comment]
1. The VPN connection screen can be better positioned. The monitor-logo under 'Status' isn't aligned properly with the word and I think 'Provider' and 'Profile' can be moved more to the left. Reasons:

- Status and Provider are rather small and fixed size (logo's) while the profile name can be potentially longer. For example: 'USA Secure Browsing' or 'Management Network VLAN332'

**Comment by dzolnai** [comment]
Ok, I just followed the design for the ratios of the columns in the status screen :) But I agree that it can be better, will be fixed

**Comment by fkooman** [comment]
Also, if you add custom providers, it is impossible to distinguish between them in the "Connect to VPN" dialog. Probably makes sense to at least show the hostname somewhere there...

**Comment by sveeke** [comment]
@dzolnai The mockups were just created to give an overall impression of the flow and look of the app, it's okay to do some stuff differently if it is better for the app :-).

**Comment by sveeke** [comment]
I'm reopening this issue for the new app styling issues :).

1) The logos/icons are not properly alligned (centered in this case) again.
2) When you add both Secure Internet and Institute Access profiles, the bottom Secure Internet profile is being capped. See the screenshot below (at Perth):

![image](https://user-images.githubusercontent.com/12334213/30083756-116a81d8-9290-11e7-8e0d-51525c993601.png)

**Comment by dzolnai** [comment]
@sveeke can you point out which logo's are not centered? I don't see any misaligned ones.
I will fix the headers to be blue with icons instead of black.
We have talked about the dropdown, it is not applicable, since items cannot be grouped.
So there will be two lists, and they are split at the center of the screen. That's why the 3rd profile is capped.

**Comment by sveeke** [comment]
Ola!

The not-centered icons are the ones in the Connection page (flag, the green computer):
![image](https://user-images.githubusercontent.com/12334213/30103259-5acf22ae-92f2-11e7-9c34-7321f1cd8ffe.png)

About the cap: I understand now, it's a scrolllist. Do you think this will be clear to all users? I would have expected a (blue in this case) scroll bar next to the list.

**Comment by fkooman** [comment]
If there are UI issues open issues for them separately, not one issue for all. Too hard to keep track. Also, not really high priority now.
