### ISSUE TITLE
Connection info is empty

### ISSUE THREAD

**Issue by sveeke** [eduvpn/android#41]
Connection info is empty on my device. @fkooman says he can see it correctly, so does not seem to be consistent. Any idea what can be wrong here?

![photo_2016-10-24_17-44-37](https://cloud.githubusercontent.com/assets/12334213/19652473/2b035462-9a11-11e6-9353-8a9d5782628b.jpg)

**Comment by sveeke** [comment]
If I can provide more data, let me know.

**Comment by dzolnai** [comment]
@sveeke I would like to know some details:
* Does this happen all the time or occasionally?
* Is this only on one device? If yes, which Android version and what is the model of your device?
* Do you see notifications? (vpn.tuxed.net has some)

**Comment by fkooman** [comment]
`vpn.tuxed.net` does not have notifications...it is also empty. I don't think any of the services have notifications at this moment.

**Comment by fkooman** [comment]
`labrat.eduvpn.nl` and `vpx.tuxed.net` have notifications now, if you disable a user in the admin it will show in the notification dialog now!

**Comment by sveeke** [comment]
@dzolnai This happens consistently (so the log was never visible). This was tested on my phone (stock OPO with latest Cyanogenmod). I will also try it on the SGS6 this afternoon.

**Comment by dzolnai** [comment]
I could not reproduce it, but I had a hunch where it might be, so I made the code more stable. I think it should be fine now, but please retest :)
