### ISSUE TITLE
better (or no) logo for "other" provider

### ISSUE THREAD

**Issue by fkooman** [eduvpn/android#43]
"HTTP" is confusing and incorrect. Not sure what exactly to put here then instead, but maybe nothing is also okay @sveeke.

**Comment by sveeke** [comment]
I'll come with a logo. What are the required dimensions?

**Comment by fkooman** [comment]
Can you not just take the eduVPN logo and make it grey-scale or give it less opacity?

**Comment by fkooman** [comment]
It would however be nice to be able to recognize _which_ custom provider it is, e.g. by its domain name.

**Comment by sveeke** [comment]
1: That was the idea yes, but dimensions would still be nice then (for the proportions).

2: And how would that be possible? Can custom instances for example host their own json file or logo on their server so the app can add it to the logo in-app? So when someones adds 'vpn.sebasveeke.nl', you get its own logo?

**Comment by fkooman** [comment]
That could be done, but would require a lot of requests to a lot of different servers, I would not recommend that. The "unlisted" VPN servers could just have a default logo with the ability to see the domain name somewhere...

**Comment by sveeke** [comment]
Since this app will can be used for Let's Connect stuff, maybe it's best to just use the Let's Connect logo for all external/custom providers. So this logo:

![logo 440x440](https://cloud.githubusercontent.com/assets/12334213/20060307/e33e0768-a4fa-11e6-93c5-25a6ef2a027c.png)

Does it have usable dimensions?

**Comment by sveeke** [comment]
There is a problem with this icon in the new app release. When te app loads all the profiles, this logo is visible on all of them for about a second, before the grey placeholder logo's will appear. This logo should only appear on the custom provider, the rest is being provided by the institution instances.
