### ISSUE TITLE
Error: State Mismatch + app crash

### ISSUE THREAD

**Issue by sveeke** [eduvpn/android#49]
Today when I used my phone, out of the blue the eduVPN popped up and showed me an error. See screenshots.

![screenshot_20161107-131611](https://cloud.githubusercontent.com/assets/12334213/20058756/dadb3b2a-a4f2-11e6-8205-dee2eefe40fc.png)

![screenshot_20161107-131642](https://cloud.githubusercontent.com/assets/12334213/20058764/dfa6225a-a4f2-11e6-8f5f-aa5059e48b6e.png)

Any idea what can be wrong @fkooman or @dzolnai ?

**Comment by fkooman** [comment]
Probably you opened your browser that still pointed to the URL that opened the app? I also saw this a couple of times as the browser does not "close" the tab that was used to open the app again after getting the approval of the user.

**Comment by sveeke** [comment]
What has the error to do with the browser? My browser was not even on today on my phone. The error comes from the app: it was connected and I had a connection, but out of the blue when I unlocked it the app gave these errors.

**Comment by fkooman** [comment]
Then I was talking about a different issue...

**Comment by dzolnai** [comment]
Was the app in the foreground (visible) when this happened @sveeke ?

**Comment by sveeke** [comment]
@dzolnai no, the app was minimized, it was active on the background. My homescreen was visible.

**Comment by fkooman** [comment]
Also saw this today spontaneously. I don't know what happened...

**Comment by dzolnai** [comment]
Can you perhaps paste logcat logs if it happened recently?

**Comment by fkooman** [comment]
I can take a look... Are you using the app yourself? It will probably also happen to you if you leave it installed and use it for a couple of days...

**Comment by dzolnai** [comment]
No, only for testing.
But I'll leave it on today, and see if I can reproduce this or the battery bug.

**Comment by dzolnai** [comment]
I merged pull #57 which will log where the app was opened from on newer devices (5.1+).
Please install this new version, and dump your logcat if it happens again.

**Comment by fkooman** [comment]
https://eduvpn.surfcloud.nl/eduvpn-20161109_01.apk

**Comment by dzolnai** [comment]
It is probably Firefox, something similar happened to me:
Opened a link from an app, selected Firefox to open it. Firefox got opened, which opened the eduVPN app then.

**Comment by sveeke** [comment]
And what can we do about this? Is there a way we can get around this issue?

**Comment by fkooman** [comment]
at least part of this is an app bug, the crash (no matter what) and also in a way the state error, it could be handled more gracefully...

**Comment by dzolnai** [comment]
The crash has probably been fixed already, at least I didn't see it happening in the latest version

**Comment by fkooman** [comment]
will open again when issue reoccurs, or create new issue.
