### ISSUE TITLE
Huge battery drain

### ISSUE THREAD

**Issue by sveeke** [eduvpn/android#55]
This morning I installed the new version of the app @fkooman told me about, but there was an almost immediate increase in power drain. Normally I have about 60-70% battery left around now (~19:30) but since the new app this went down to 16%. In the Battery settings menu (where you can see which apps use the battery) eduVPN always was third or fourth in the list, but now eduVPN is first.

@fkooman just send me the newest version of the eduVPN app so I will check again tomorrow. If it's normal again I will close it.

By the way: I changed the battery settings on the eduVPN app as you said in [this issue](https://github.com/eduvpn/android/issues/40) just now, so that has not affected the battery life till now.

**Comment by dzolnai** [comment]
This is very interesting, because the only cause could be the library (since only that is running when the app is in the background), but I didn't make any major library changes through the versions.

Perhaps you were using a VPN profile, which has some kind of `keep alive` property, which didn't allow your device to sleep?
If you tap on EduVPN in the battery view, what does it say under `Keep awake` and `CPU total`?

**Comment by fkooman** [comment]
Could it be that I know build the library myself? I doubt it...but in theory it is possible right?

**Comment by dzolnai** [comment]
I don't think so, the native build commands are the same.

**Comment by sveeke** [comment]
I seem to have less issues with battery drain! I'll check CPU total this evening when the battery is drained some more (it's been three hours since the phone got off the power grid).

**Comment by sveeke** [comment]
I have new phone that does not have these issues. So let's hope the problem was with my old phone and not with the app.

**Comment by sveeke** [comment]
It seems that this issue still exists. Since the eduVPN app is being tested by a few dozen people a rather large part (5 so far) complains about battery drain caused by the eduVPN app. 

I try to convince some of them to install OpenVPN for Android to see if that works better and will report back here.

**Comment by sveeke** [comment]
Phones and Android versions that are affected:
* Samsung S5 Neo with Android-versie 6.0.1
* Motorola Moto G

[User screenshot](http://pasteboard.co/EzLhttgNm.png)

**Comment by sveeke** [comment]
Usefull information: https://github.com/jlund/streisand/issues/465

We use a fedault of 10 60: https://github.com/eduvpn/vpn-server-node/blob/9f8a314dbccb5d2b3f0d10a626ccb5301b0da738/src/OpenVpn.php#L168

This might be (one of) the reason of the perceived battery drain.

The reason it's this low (even lower than the default in OpenVPN according to the GitHub issue) is because of UDP through NAT: NAT routers will close the connection otherwise.

**Comment by sveeke** [comment]
Other phones of users with high battery drain:

* Updated Samsung Galaxy S6. Idle for most of the day, 35% battery consumption.
* Google Nexus 5X with Android 7.1.1: 30% battery consumption after 15 hours of mostly idle time.
* One of the newer Sony Android devices (type unknown to me): 37% battery consumption after moderate use.

Around one in three users complain about it, I'm pretty sure this problem will limit the app succes if we don't fix it.

**Comment by fkooman** [comment]
Can you reproduce this with OpenVPN for Android?

**Comment by sveeke** [comment]
I myself don't have these issues anymore since I have got my new phone, but one of the users was willing to try it on his phone. He runs eduVPN today, tomorrow and tuesday. He will use OpenVPN for Android (the F-Droid version) the three days after that and provide all the statistiscs off all days to us.

I'm still trying to find other users who will test this a couple of days, but most of them find it to be too much of a hassle or are afraid they forget to make screenshots before they put the power connector in the phone (which will reset the battery stats).

**Comment by fkooman** [comment]
@sveeke still an issue with latest version?

**Comment by fkooman** [comment]
Create new issue when needed. But then also include comparison with "OpenVPN for Android", otherwise pointless.
