### ISSUE TITLE
change client_id and redirect_uri

### ISSUE THREAD

**Issue by fkooman** [eduvpn/android#58]
Proposal:

`client_id`: `nl.eduvpn.app`
`redirect_uri`: `nl.eduvpn.app://import`

**Comment by dzolnai** [comment]
I don't think schemes can contain dots

**Comment by fkooman** [comment]
That's why I checked it before proposing it ;) 
```
      scheme      = ALPHA *( ALPHA / DIGIT / "+" / "-" / "." )
```

https://tools.ietf.org/html/rfc3986#section-3.1

**Comment by fkooman** [comment]
i updated the servers to also support the new client_id, while still keeping the old one for now as well.

**Comment by fkooman** [comment]
https://eduvpn.surfcloud.nl/app/eduvpn-20161110.apk

tested, and works!
