### ISSUE TITLE
Could not fetch all profiles

### ISSUE THREAD

**Issue by efef** [eduvpn/android#59]
I disconnected the VPN, put my tablet in my pocket and a few minutes later I got the error "Cloud not fetch all profiles" (see screenshot below)

My guess is that the internet connection was not available and therefor the profiles couldn't get downloaded.
I could solve it by clicking on the exclamation mark and click retry, however it would be much better if the app itself would auto-retry to load the profiles. For example every minute.

![screenshot_2016-11-10-11-36-22](https://cloud.githubusercontent.com/assets/3393474/20174056/5eed2a04-a73c-11e6-8eca-64a42a76a614.png)

**Comment by fkooman** [comment]
>  For example every minute

You mean only when the user is actually using the app right? I guess retry 3 times makes more sense, or, detect if there is an Internet connection before actually trying.

**Comment by dzolnai** [comment]
Current implementation is retry once.

**Comment by fkooman** [comment]
![screenshot_20161110-200547](https://cloud.githubusercontent.com/assets/616885/20190327/4884f5ae-a781-11e6-882c-a2be384445ee.png)

**Comment by fkooman** [comment]
@efef saw this behavior as well, it is a bit weird to have double buttons there :)

**Comment by dzolnai** [comment]
Do you have two added providers?
There should be a row between them for the other provider btw

**Comment by fkooman** [comment]
Yes, two providers.

There should be a row but there isn't?

**Comment by dzolnai** [comment]
Yes between the two row of buttons, a one similar to labrat one. I'll look into it.

**Comment by sveeke** [comment]
What is the status on this issue? :)

**Comment by dzolnai** [comment]
There was a lookup issue where it found the wrong items on the layout. Fixed, it should look good now.
