### ISSUE TITLE
companion app approval in browser doesn't disappear

### ISSUE THREAD

**Issue by efef** [eduvpn/android#60]
After first-time login I need to 'approve the companion-app'. This is a webbrowser event and after clicking on 'approve' I will be back in the eduVPN app. However the 'old' approval screen is still in my browser (screenshot 1), so I can click a second time on 'approve'. When clicking the second time on 'approve' I'll get an error in the app (screenshot 2).
Would be better to close the browser tab after clicking on 'approve'

screenshot 1
![screenshot_2016-11-10-11-20-45](https://cloud.githubusercontent.com/assets/3393474/20174452/1c8e3f48-a73e-11e6-8732-9e9a2d74c9e9.png)
screenshot 2 (error message)
![screenshot_2016-11-10-11-59-24](https://cloud.githubusercontent.com/assets/3393474/20174460/2be547f2-a73e-11e6-978b-87593d98c21d.png)

**Comment by fkooman** [comment]
If we get rid of the 'confirm' dialog (https://github.com/eduvpn/vpn-user-portal/issues/48) this would be worse I guess, as it will keep opening the app over and over again, not giving time to close the tab I guess? 

I am not sure the app can close the browser tab, or if it could, then only in the 'embedded browser' scenario...

**Comment by dzolnai** [comment]
> I am not sure the app can close the browser tab

It cannot.

> then only in the 'embedded browser' 

In custom tabs the sessions are destroyed after leaving them, so in that case, yes, it will be closed.

**Comment by fkooman** [comment]
is an issue with using external browser.
