### ISSUE TITLE
no internet - java errors

### ISSUE THREAD

**Issue by efef** [eduvpn/android#61]
I experienced some java-errors but couldn't re-enact the root-cause.
However when I disconnect in the app, turn-off WiFi on my tablet, click on the profile 'internet access' I get a few java errors. See screenshot for 1 error

Would be better if non-internet connectivity errors would be handled in a more smooth notification.

![screenshot_2016-11-10-12-21-45](https://cloud.githubusercontent.com/assets/3393474/20174964/d87478d8-a740-11e6-84bf-6be2e1a0d276.png)

**Comment by fkooman** [comment]
I guess the app could detect if there is Internet connectivity before trying, I think there's an Android API for that.

**Comment by sveeke** [comment]
What is the status of this issue?
