### ISSUE TITLE
not able to stop connection attempts

### ISSUE THREAD

**Issue by fkooman** [eduvpn/android#63]
when trying to connect to a profile, which for example has a DNS name assigned to it that does not resolve, but maybe there are other cases, the app keeps trying to connect (yellow icon), but there is no option to cancel the connection attempt except closing the app.

The "back" button is grey and unclickable. Maybe make the back button work, or replace it with a "stop" button while trying to connect.

**Comment by fkooman** [comment]
I think I have to actuall go to "Apps" in the settings and kill it there, just "swiping" it away is not enough.

**Comment by dzolnai** [comment]
Should not happen anymore, fixed.

**Comment by fkooman** [comment]
It is okay for the disconnect button to be always available, there is no 5 second delay needed.

**Comment by dzolnai** [comment]
Fixed by #73
