### ISSUE TITLE
Small text issue:  Provider added. You can now select more profiles

### ISSUE THREAD

**Issue by sveeke** [eduvpn/android#69]
`<string name="provider_added_new_configs_available">Provider added. You can now select more profiles.</string>
`
You can only select one profile, not two, so it can be confusing to users. So it would be something like "Provider added. You can now select your profile".

**Comment by dzolnai** [comment]
It was meant in the sense, that more profiles than before (so it might have been 0 in the past, and now it is 1, since the user added a new provider). But I agree, it is confusing :)

**Comment by sveeke** [comment]
I see, so the message was correct. Indeed confusing, since it's a quite logical statement :).

**Comment by dzolnai** [comment]
Fixed the message to your suggestion.
