### ISSUE TITLE
Remove SSL3 support

### ISSUE THREAD

**Issue by sveeke** [eduvpn/android#80]
An error occured on a Samsung Galaxy S3 with Android version 4.2.x, SSL3 must be removed from the app so it cannot fallback on it.

[Screenshot](https://cupcake.sebasveeke.nl/download/photo-ssl3.jpg)

http://stackoverflow.com/questions/29916962/javax-net-ssl-sslhandshakeexception-javax-net-ssl-sslprotocolexception-ssl-han

**Comment by fkooman** [comment]
It is not a bug, it is a feature. The server (both the HTTPS server with the API and the OpenVPN server) does not support anything other than TLS 1.2.

https://github.com/eduvpn/documentation/blob/6aa3ec3b02c781cfb8df33e273105c45e7132fe3/resources/ssl.conf

**Comment by fkooman** [comment]
See also: https://www.ssllabs.com/ssltest/analyze.html?d=labrat.eduvpn.nl&s=2001%3a610%3a188%3a2011%3a145%3a100%3a179%3a6&hideResults=on&latest Android >= 4.4.2 should work by the way.

**Comment by sveeke** [comment]
The bug label is for the app and not the server code. If I understand correctly the server supports only the right crypto, but the app supports also the older SSLv3. Of course the server will block devices that want to use older crypto (as intended, that's the feature), but why not remove it from the app then? Less code = good?

**Comment by fkooman** [comment]
Because the problem is in the Android base system, not in the application. I think the error is actually not related to SSLv3 at all, but indicates that there is no suitable protocol to negotiate as it does not support TLSv1.2.

**Comment by fkooman** [comment]
Whether or not to fix this for this particular instance, i.e. old Android versions, I guess it depends on whether or not you want to "encourage" people to use old devices that are known to not be secure (at all), i.e. didn't receive security updates for years now.

Maybe using a VPN on top of a known insecure device actually makes things safer in the end, if the alternative is for the user to continue without VPN, but I'd be careful with giving users a false sense of security in where using a VPN makes them think things will be secure now and nothing can happen...

**Comment by fkooman** [comment]
As we require Android 5 anyway with the new version, this is no longer relevant.
