### ISSUE TITLE
Remove profile function unclear for users

### ISSUE THREAD

**Issue by sveeke** [eduvpn/android#81]
Multiple users that test the app complained about 'the lack of a way to remove a profile'. After I explained that they have to swipe the profile entry to either side of the screen, most of them looked at me with a look that said: "how should I have known this?!"

Conclusion: the current method is not intuïtive / clear enough and causes more confusion than should be the case with such a simple feature. In 1.1 we should look at other options, like a dedicated button or a text that explains how the current method should be used. 

Then again: if you need text to explain how something works, it's broken to begin with from a UI design perspective.

**Comment by fkooman** [comment]
I think the convention on Android is to "hold" and then a popup menu should appear.

**Comment by shaanen** [comment]
In the current situation, the profile is only removed after the "undo" prompt is gone. So if you connect with another profile before the prompt is gone, it is not removed. It is also not clear beforehand that removing a profile will also remove all other profiles belonging to that same provider. The popup menu @fkooman suggested could mention that.

**Comment by dzolnai** [comment]
Servers can now be removed by long pressing on them.
