### ISSUE TITLE
disconnect 'hang'

### ISSUE THREAD

**Issue by efef** [eduvpn/android#82]
Quite regularly when I click "disconnect" the screen seems to be hanging. Nothing happens at all. I can 'fix' it by pressing 'connection info', go to "view log" and go back. Or I go to another app and go back to eduVPN to see the connection was disconnected and I'm able to setup a new one.

In order to re-enact this issue. Start a VPN and immediately click on disconnect. After a few times 'connect' and 'disconnect' the issue will happen.

**Comment by fkooman** [comment]
@efef is this fixed in the last development version?

**Comment by dzolnai** [comment]
Fixed, please reopen if it still happens
