### ISSUE TITLE
'notification' API

### ISSUE THREAD

**Issue by fkooman** [eduvpn/android#9]
There is an idea for a notification API, see also https://github.com/eduvpn/documentation/blob/master/API.md this is not yet implemented. Do you guys have some feedback what would be best for the app?

**Comment by dzolnai** [comment]
Should these notifications appear as system notifications ([example](http://docs.urbanairship.com/_images/default-factory-notification1.png))?

**Comment by fkooman** [comment]
I don't really mind. I think the screenshots in the design show them "in-app" and not as a (proper) Android notification. See https://github.com/eduvpn/documentation/blob/master/app/android.md for the screenshots. 

What do you say @sveeke? 

But I was more wondering about the API itself (content of messages, formats of data etc.), not so much how it looks in the app, as this API will (probably) be used by other apps as well...

**Comment by dzolnai** [comment]
I was wondering because if they would be system notifications, then they should be fetched periodically also when the app is in the background.

About the API: 
* I would include the seconds in the date as well.
* Are there any other types? If yes, document them, otherwise it is probably a redundant field.
* Messages should only be visible until they are relevant.
* A GUID would indeed be fine, but otherwise the date can be used as well as a guid.
* How often we would need to fetch: If it would only be visible on the VPN connection screen, I would say hourly while the user is connected.

**Comment by fkooman** [comment]
> I was wondering because if they would be system notifications, then they should be fetched periodically also when the app is in the background.

True, this could be done once per day I guess.

> I would include the seconds in the date as well. 

Fair.

> Are there any other types? If yes, document them, otherwise it is probably a redundant field.

Currently not, but I guess if they become available we could update the API version.

> Messages should only be visible until they are relevant.

But this is a bit of a problem. A user block may be relevant until it is undone. Maintainance will be in the future, so maybe it makes sense to include some extra "types" where maintenance is its own type.

> A GUID would indeed be fine, but otherwise the date can be used as well as a guid.

Okay!

> How often we would need to fetch: If it would only be visible on the VPN connection screen, I would say hourly while the user is connected. 

I guess on/before connect and on/after disconnect. And then if the app is not used, every day?

**Comment by dzolnai** [comment]
I agree with everything.

And then if the app is not used, every day?

But since the app is not used, the user will not be able to see them, so this is just wasting battery in my opinion.

**Comment by fkooman** [comment]
> I agree with everything.

Too easy! ;) 

> And then if the app is not used, every day? But since the app is not used, the user will not be able to see them, so this is just wasting battery in my opinion.

Well, I am not sure how much battery is wasted by querying an endpoint every day... maybe you can distinguish between "just installed" and actually running? I guess obtaining the (system) messages only when the user opens the application is also acceptable. And before connecting and after disconnecting also fetch the (user) messages...

I updated the API document here with the stuff we talked about: https://github.com/eduvpn/documentation/blob/master/API.md#system-messages hope I got most stuff right :)

**Comment by dzolnai** [comment]
When user opens the app is a better option indeed.

**Comment by fkooman** [comment]
implemented.
