### ISSUE TITLE
only one "other" needed

### ISSUE THREAD

**Issue by fkooman** [eduvpn/android#91]
Now there is an "Other" option at both "Secure Internet" and "Institute Access" after choosing either of them. The "Other" should be on the screen where you choose "Secure Internet" or "Institute Access".

**Comment by dzolnai** [comment]
Would the authorization type in this case always be local?
Do we have a design for this version of the screen?

**Comment by fkooman** [comment]
> Would the authorization type in this case always be local?

Yes.

**Comment by fkooman** [comment]
https://github.com/eduvpn/artwork/tree/master/styling

**Comment by dzolnai** [comment]
Fixed, closing.
