### ISSUE TITLE
Need access token first from "home institute"

### ISSUE THREAD

**Issue by fkooman** [eduvpn/android#93]
If you want to add a provider where the

    "authorization_type": "distributed",

one needs to _first_ obtain an access token from the institute where they can actually authenticate. So, in case of eduVPN, a Dutch student would need to first choose "Netherlands", authenticate there, and only after that succeeds can they choose any other country.

The UI should be a little updated to make that clear to the user that they first have to choose their own country/region or organization where they have an account.

**Comment by dzolnai** [comment]
👍  Please provide a design for it

**Comment by fkooman** [comment]
@sveeke

**Comment by fkooman** [comment]
https://github.com/eduvpn/artwork/tree/master/styling

**Comment by dzolnai** [comment]
Fixed, closing.
