### ISSUE TITLE
Error creating keypair

### ISSUE THREAD

**Issue by mkoelewijn** [eduvpn/android#97]
When you create a 'Secure Internet' profile (which works) and afterwords a "Institute Access" profile the following error appears:

Unexpected problem: Error creating keypair. Details: nl.eduvpn.app.service.APIService$UserNotAuthorizedException

The same happens when you first create a "Institute Access" profile, then the "Secure Internet" will give the error.

**Comment by sveeke** [comment]
I have the same issue. See:

![image](https://user-images.githubusercontent.com/12334213/30083151-afb7b2c8-928d-11e7-99d2-1da3a230232e.png)

**Comment by dzolnai** [comment]
Fixed in latest version
